package com.dollyplastic.invoiceapp.pdf
import com.dollyplastic.invoiceapp.data.models.Invoice
import com.dollyplastic.invoiceapp.data.models.TransportMode
import com.itextpdf.barcodes.BarcodeQRCode
import com.itextpdf.kernel.colors.DeviceGray
import com.itextpdf.layout.Document
import com.itextpdf.layout.borders.Border
import com.itextpdf.layout.element.Cell
import com.itextpdf.layout.element.Image
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.element.Table
import com.itextpdf.layout.properties.AreaBreakType
import com.itextpdf.layout.properties.HorizontalAlignment
import com.itextpdf.layout.properties.TextAlignment
import com.itextpdf.layout.properties.UnitValue


// ==========================================
    // E-WAY BILL PAGE GENERATOR
    // ==========================================
internal fun drawEWayBillPage(document: Document, invoice: Invoice) {
        // Start a new page
        document.add(com.itextpdf.layout.element.AreaBreak(AreaBreakType.NEXT_PAGE))
        
        // 1. Title "e-Way Bill"
        document.add(Paragraph("e-Way Bill")
            .setTextAlignment(TextAlignment.CENTER)
            .setBold()
            .setFontSize(10f)
            .setMarginBottom(10f)
        )

        // 2. QR Code (Center)
        // QR Text: Use SignedQRCode if available (from E-Invoice), else JSON of details
        val qrText = if (!invoice.eInvoiceDetails?.signedQrCode.isNullOrBlank()) {
             invoice.eInvoiceDetails!!.signedQrCode
        } else {
             // Fallback JSON
             "{\"ewbNo\":\"${invoice.eWayBillDetails?.ewayBillNo}\",\"date\":\"${invoice.eWayBillDetails?.ewayBillDate}\"}"
        }
        
        try {
            val qrCode = BarcodeQRCode(qrText)
            val qrImage = Image(qrCode.createFormXObject(document.pdfDocument))
            qrImage.setWidth(100f).setHeight(100f)
            qrImage.setHorizontalAlignment(HorizontalAlignment.CENTER)
            document.add(qrImage)
        } catch(e: Exception) {
            document.add(Paragraph("[QR Code]").setTextAlignment(TextAlignment.CENTER))
        }

        document.add(Paragraph("").setMarginBottom(15f)) // Spacer


        // Helper for Key-Value Rows (No Border)
        fun addRow(table: Table, label: String, value: String) {
            table.addCell(Cell().add(Paragraph(label).setFontSize(9f).setBold()).setBorder(Border.NO_BORDER))
            table.addCell(Cell().add(Paragraph(": $value").setFontSize(9f)).setBorder(Border.NO_BORDER))
        }

        // 3. E-Way Bill Details Header (Labels 30%, Value 70%)
        val headerTable = Table(UnitValue.createPercentArray(floatArrayOf(30f, 70f))).useAllAvailableWidth()
        
        val ewb = invoice.eWayBillDetails
        addRow(headerTable, "E-Way Bill No", ewb?.ewayBillNo ?: "")
        addRow(headerTable, "E-Way Bill Date", ewb?.ewayBillDate ?: "")
        addRow(headerTable, "Generated By", ewb?.generatedBy ?: "")
        addRow(headerTable, "Valid From", ewb?.validFrom ?: "") // Use new Valid From field
        addRow(headerTable, "Valid Until", ewb?.validUpto ?: "")
        
        document.add(headerTable)
        drawSeparator(document)


        // 4. IRN Details (Only if E-Invoice exists)
        if (invoice.eInvoiceDetails != null && invoice.eInvoiceDetails.irn.isNotBlank()) {
             document.add(Paragraph("IRN Details").setBold().setFontSize(9f))
             val irnTable = Table(UnitValue.createPercentArray(floatArrayOf(30f, 70f))).useAllAvailableWidth()
             addRow(irnTable, "IRN", invoice.eInvoiceDetails.irn)
             addRow(irnTable, "Ack No.", invoice.eInvoiceDetails.ackNo)
             addRow(irnTable, "Ack Date", invoice.eInvoiceDetails.ackDate)
             document.add(irnTable)
             drawSeparator(document)
        }


        // 5. Part - A
        document.add(Paragraph("Part - A").setBold().setFontSize(9f).setUnderline())
        val partATable = Table(UnitValue.createPercentArray(floatArrayOf(30f, 70f))).useAllAvailableWidth()

        // Supplier
        val sellerAddr = "${invoice.firm.addressLine1} ${invoice.firm.addressLine2} , ${invoice.firm.city} ${invoice.firm.state} ${invoice.firm.pincode}"
        addRow(partATable, "GSTIN of Supplier", invoice.firm.gstin)
        addRow(partATable, "Place of Dispatch", sellerAddr)

        // Recipient
        val buyer = invoice.shipToParty ?: invoice.billToParty // Ship To takes priority for delivery
        val buyerAddr = "${buyer?.addressLine1} ${buyer?.addressLine2}, ${buyer?.city} ${buyer?.state} ${buyer?.pincode}"
        addRow(partATable, "GSTIN of Recipient", "${buyer?.gstin}")
        addRow(partATable, "Place of Delivery", buyerAddr)

        // Doc Details
        addRow(partATable, "Document No.", invoice.invoiceNumber)
        addRow(partATable, "Document Date", invoice.invoiceDate)
        addRow(partATable, "Transaction Type", "Regular") // Assumed
        addRow(partATable, "Value of Goods", "%.2f".format(invoice.totalInvoiceValue))
        
        // HSN Code (Just first one or 'Multiple')
        val hsn = if(invoice.items.isNotEmpty()) invoice.items[0].item.hsnCode else ""
        addRow(partATable, "HSN Code", hsn)
        
        addRow(partATable, "Supply Type", "Outward - Supply")
        
        // Transporter
        val transporter = "${invoice.transportDetails.transporterId ?: ""} - ${invoice.transportDetails.transporterName ?: ""}"
        addRow(partATable, "Transporter", transporter)
        
        document.add(partATable)
        drawSeparator(document)


        // 6. Part - B (Table)
        document.add(Paragraph("Part - B").setBold().setFontSize(9f).setUnderline().setMarginBottom(5f))

        // Columns: Mode, Vehicle/Doc, From, Entered Date, Entered By, CEWB
        val partBTable = Table(UnitValue.createPercentArray(floatArrayOf(10f, 25f, 20f, 15f, 20f, 10f))).useAllAvailableWidth()
        
        // Headers
        fun addHeader(text: String) {
            partBTable.addCell(Cell().add(Paragraph(text).setBold().setFontSize(8f)).setBackgroundColor(DeviceGray(0.9f)))
        }
        addHeader("Mode")
        addHeader("Vehicle / Trans\nDoc No & Dt.")
        addHeader("From")
        addHeader("Entered\nDate")
        addHeader("Entered By")
        addHeader("CEWB No.\n(if any)")

        // Data Row (Single Row based on current data)
        fun addData(text: String) {
             partBTable.addCell(Cell().add(Paragraph(text).setFontSize(8f)))
        }
        
        // Mode Mapping
        val mode = when(invoice.transportDetails.mode) {
            TransportMode.ROAD  -> "1 - Road"
            TransportMode.RAIL  -> "2 - Rail"
            TransportMode.AIR ->  "3 - Air"
            TransportMode.SHIP ->  "4 - Ship"
        }
        
        val docDetails = if(!invoice.transportDetails.vehicleNumber.isNullOrBlank())
            invoice.transportDetails.vehicleNumber
                         else 
                           "${invoice.transportDetails.transporterDocNo} / ${invoice.transportDetails.transporterDocDate}"

        addData(mode)
        addData(docDetails)
        addData(invoice.firm.city) // From (Dispatch City)
        addData(ewb?.ewayBillDate ?: "") // Entered Date (Approx)
        addData(invoice.firm.gstin) // Entered By (Self)
        addData("") // CEWB

        document.add(partBTable)
    }

    private fun drawSeparator(document: Document) {
        document.add(com.itextpdf.layout.element.LineSeparator(com.itextpdf.kernel.pdf.canvas.draw.SolidLine(0.5f)).setMarginTop(5f).setMarginBottom(5f))
    }
