package com.dollyplastic.invoiceapp.ui.screens.processing.components

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CornerSize
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

@Composable
fun ScrapeVerificationSheet(
    dataList: List<Map<String, String>>,
    targetInvoiceNumber: String,
    portalMode: String = "EWAY",
    onConfirm: (Map<String, String>) -> Unit,
    onCancel: () -> Unit,
    modifier: Modifier = Modifier
) {
    // 1. Auto-Select Logic
    // Find index of item where 'Doc No' or 'Invoice No' matches target
    val initialIndex = remember(dataList) {
        val index = dataList.indexOfFirst { map ->
            val docNo = map["Doc. No"] ?: map["Invoice No"] ?: ""
            // Simple cleanup for comparison (trim spaces, ignore case)
            docNo.trim().equals(targetInvoiceNumber.trim(), ignoreCase = true)
        }
        if (index != -1) index else 0 // Default to first if no match
    }

    var selectedIndex by remember { mutableStateOf(initialIndex) }
    
    // Binding Fields to Selected Item
    val selectedData = dataList.getOrNull(selectedIndex) ?: emptyMap()
    
    // Mutable State for editing (re-initialized when selectedIndex changes)
    // E-WAY Fields
    var ewbNo by remember(selectedIndex) { mutableStateOf(selectedData["E-Way Bill No"] ?: "") }
    var ewbDate by remember(selectedIndex) { mutableStateOf(selectedData["E-Way Bill Date"] ?: "") }
    var validUntil by remember(selectedIndex) { mutableStateOf(selectedData["Valid Until"] ?: "") }
    var validFrom by remember(selectedIndex) { mutableStateOf(selectedData["Valid From"] ?: "") }
    var generatedBy by remember(selectedIndex) { mutableStateOf(selectedData["Generated By"] ?: "") }

    // E-INVOICE Fields
    var irn by remember(selectedIndex) { mutableStateOf(selectedData["IRN"] ?: "") }
    var ackNo by remember(selectedIndex) { mutableStateOf(selectedData["Ack No"] ?: "") }
    var ackDate by remember(selectedIndex) { mutableStateOf(selectedData["Ack Date"] ?: "") }
    var status by remember(selectedIndex) { mutableStateOf(selectedData["Status"] ?: "") }


    Surface(
        modifier = modifier.fillMaxWidth(),
       // tonalElevation = 8.dp, // Removing heavy elevation for split-screen look
        color = MaterialTheme.colorScheme.surface
    ) {
        Column(
            modifier = Modifier
                .padding(16.dp)
                .fillMaxSize()
        ) {
            Text(
                text = if (portalMode == "EWAY") "Verify E-Way Bill" else "Verify E-Invoice",
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold,
                modifier = Modifier.padding(bottom = 12.dp)
            )

            // TILE LIST (Only if > 1 item)
            if (dataList.size > 1) {
                Text(
                    text = "Multiple entries found. Select match:",
                    style = MaterialTheme.typography.labelMedium,
                    color = MaterialTheme.colorScheme.primary
                )
                Spacer(Modifier.height(8.dp))
                LazyRow(
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    items(dataList.size) { index ->
                        val item = dataList[index]
                        val isSelected = index == selectedIndex
                        val docNo = item["Doc. No"] ?: item["Invoice No"] ?: "Unknown"
                        val date = if(portalMode == "EWAY") (item["E-Way Bill Date"] ?: "No Date") else (item["Ack Date"] ?: "No Date")
                        
                        Card(
                            onClick = { selectedIndex = index },
                            colors = CardDefaults.cardColors(
                                containerColor = if (isSelected) MaterialTheme.colorScheme.primaryContainer else MaterialTheme.colorScheme.surfaceVariant
                            ),
                            border = if (isSelected) androidx.compose.foundation.BorderStroke(2.dp, MaterialTheme.colorScheme.primary) else null
                        ) {
                            Column(Modifier.padding(8.dp)) {
                                Text(docNo, style = MaterialTheme.typography.bodyMedium, fontWeight = FontWeight.Bold)
                                Text(date, style = MaterialTheme.typography.bodySmall)
                            }
                        }
                    }
                }
                Divider(Modifier.padding(vertical = 12.dp))
            } else if (dataList.isEmpty()) {
                 Text("No data to verify.", color = MaterialTheme.colorScheme.error)
            }


            // EDITOR FORM
            Column(
                modifier = Modifier
                    .weight(1f)
                    .verticalScroll(rememberScrollState()),
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                if (portalMode == "EWAY") {
                    OutlinedTextField(
                        value = ewbNo,
                        onValueChange = { ewbNo = it },
                        label = { Text("E-Way Bill No") },
                        modifier = Modifier.fillMaxWidth(),
                        singleLine = true
                    )
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        OutlinedTextField(
                            value = ewbDate,
                            onValueChange = { ewbDate = it },
                            label = { Text("Date") },
                            modifier = Modifier.weight(1f),
                            singleLine = true
                        )
                        OutlinedTextField(
                            value = validUntil,
                            onValueChange = { validUntil = it },
                            label = { Text("Valid Until") },
                            modifier = Modifier.weight(1f),
                            singleLine = true
                        )
                    }
                     OutlinedTextField(
                        value = validFrom,
                        onValueChange = { validFrom = it },
                        label = { Text("Valid From") },
                        modifier = Modifier.fillMaxWidth(),
                        singleLine = true
                    )
                    OutlinedTextField(
                        value = generatedBy,
                        onValueChange = { generatedBy = it },
                        label = { Text("Generated By") },
                        modifier = Modifier.fillMaxWidth()
                    )
                } else if (portalMode == "EINVOICE_AND_EWAY") {
                    // COMBINED FORM
                    Text("E-Invoice Details", style=MaterialTheme.typography.labelMedium, color=MaterialTheme.colorScheme.primary)
                    OutlinedTextField(
                        value = ackNo,
                        onValueChange = { ackNo = it },
                        label = { Text("Ack No") },
                        modifier = Modifier.fillMaxWidth(),
                        singleLine = true
                    )
                     OutlinedTextField(
                        value = ackDate,
                        onValueChange = { ackDate = it },
                        label = { Text("Ack Date") },
                        modifier = Modifier.fillMaxWidth(),
                        singleLine = true
                    )
                    OutlinedTextField(
                        value = irn,
                        onValueChange = { irn = it },
                        label = { Text("IRN") },
                        modifier = Modifier.fillMaxWidth(),
                        maxLines = 2
                    )
                    
                    Divider(Modifier.padding(vertical=8.dp))
                    Text("E-Way Bill Details", style=MaterialTheme.typography.labelMedium, color=MaterialTheme.colorScheme.primary)
                     
                    OutlinedTextField(
                        value = ewbNo,
                        onValueChange = { ewbNo = it },
                        label = { Text("E-Way Bill No") },
                        modifier = Modifier.fillMaxWidth(),
                        singleLine = true
                    )
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        OutlinedTextField(
                            value = ewbDate,
                            onValueChange = { ewbDate = it },
                            label = { Text("Date") },
                            modifier = Modifier.weight(1f),
                            singleLine = true
                        )
                        OutlinedTextField(
                            value = validUntil,
                            onValueChange = { validUntil = it },
                            label = { Text("Valid Until") },
                            modifier = Modifier.weight(1f),
                            singleLine = true
                        )
                    }
                     OutlinedTextField(
                        value = validFrom,
                        onValueChange = { validFrom = it },
                        label = { Text("Valid From") },
                        modifier = Modifier.fillMaxWidth()
                    )
                    OutlinedTextField(
                        value = generatedBy,
                        onValueChange = { generatedBy = it },
                        label = { Text("Generated By") },
                        modifier = Modifier.fillMaxWidth()
                    )

                } else {
                    // E-INVOICE FORM
                    OutlinedTextField(
                        value = ackNo,
                        onValueChange = { ackNo = it },
                        label = { Text("Ack No") },
                        modifier = Modifier.fillMaxWidth(),
                        singleLine = true
                    )
                     OutlinedTextField(
                        value = ackDate,
                        onValueChange = { ackDate = it },
                        label = { Text("Ack Date") },
                        modifier = Modifier.fillMaxWidth(),
                        singleLine = true
                    )
                    OutlinedTextField(
                        value = irn,
                        onValueChange = { irn = it },
                        label = { Text("IRN") },
                        modifier = Modifier.fillMaxWidth(),
                        maxLines = 3 // IRN is long
                    )
                     OutlinedTextField(
                        value = status,
                        onValueChange = { status = it },
                        label = { Text("Status") },
                        modifier = Modifier.fillMaxWidth(),
                        singleLine = true
                    )
                }
            }

            // ACTION BUTTONS
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(top = 8.dp),
                horizontalArrangement = Arrangement.spacedBy(16.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                OutlinedButton(
                    onClick = onCancel,
                    modifier = Modifier.weight(1f)
                ) {
                    Text("Discard")
                }
                Button(
                    onClick = {
                        if (portalMode == "EWAY") {
                            onConfirm(
                                mapOf(
                                    "E-Way Bill No" to ewbNo,
                                    "E-Way Bill Date" to ewbDate,
                                    "Valid Until" to validUntil,
                                    "Valid From" to validFrom,
                                    "Generated By" to generatedBy
                                )
                            )
                        } else if (portalMode == "EINVOICE_AND_EWAY") {
                             onConfirm(
                                mapOf(
                                    "IRN" to irn,
                                    "Ack No" to ackNo,
                                    "Ack Date" to ackDate,
                                    "Status" to status,
                                    "E-Way Bill No" to ewbNo,
                                    "E-Way Bill Date" to ewbDate,
                                    "Valid Until" to validUntil,
                                    "Valid From" to validFrom,
                                    "Generated By" to generatedBy
                                )
                            )
                        } else {
                            onConfirm(
                                mapOf(
                                    "IRN" to irn,
                                    "Ack No" to ackNo,
                                    "Ack Date" to ackDate,
                                    "Status" to status
                                )
                            )
                        }
                    },
                    modifier = Modifier.weight(1f)
                ) {
                    Text("Import Selected")
                }
            }
        }
    }
}
